title: "Anshul Garg - Portfolio"
description: "Principal Engineer | Cloud, DevOps & Platform Engineering | AWS Certified"
theme: minima

# Optional extras for Minima theme
show_excerpts: true        # shows a short intro for posts if you add any later
minima:
  skin: classic            # clean look (other options: dark, auto, solarized, etc.)
  social_links:
    github: garganshulgarg
    linkedin: anshul-garg-cse
